stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR

  variables:
  - group: vwon23
  - name: 'tag'
    value: '$(Build.BuildId)'
  - name: 'imagelabel'
    value: 'ECS_SERVICES'
  - name: 'ADORepoName'
    value: $(ECSServicesRepo)

  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image to ECR

    steps:
    - bash: |
        cd $(System.DefaultWorkingDirectory)
        docker build --label $(imagelabel)_$(tag) -t $(ADORepoName) .
      displayName: Build an image

    - bash: |
        aws ecr get-login-password --region $(AWSRegion) | docker login --username AWS --password-stdin $(SSProdAccountID).dkr.ecr.$(AWSRegion).amazonaws.com
        docker tag $(ADORepoName) $(SSProdAccountID).dkr.ecr.$(AWSRegion).amazonaws.com/$(ADORepoName):latest
        docker push $(SSProdAccountID).dkr.ecr.$(AWSRegion).amazonaws.com/$(ADORepoName):latest
      displayName: Push an image to AWS ECR